#!/usr/bin/env bash

((!$#)) && {
    echo Error: no branch name provided
    exit 1
}

(($# > 1)) && {
    echo Error: too many arguments
    exit 1
}

git branch "$1" &&
    git checkout "$1" &&
    git branch

exit $?
