#!/usr/bin/env bash

((!$#)) && {
    echo Error: no version provided
    exit 1
}

(($# > 1)) && {
    echo Error: too many arguments
    exit 1
}

[[ ! $1 =~ ^[0-9]+(\.[0-9]+)?(\.[0-9]+)?(-[a-zA-Z]+(\.)?[0-9]+)?$ ]] && {
    echo Error: invalid version
    exit 1
}

git tag -a "v$1" -m "v$1" &&
    git log -1 "v$1"

exit $?
